import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from "react-native-responsive-screen";
import { StyleSheet } from "react-native";
import colors from "../../../Assets/Colors/colors";
//================================ Local Imported Files ======================================//
const Styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.bright_white,
  },
  headerView: {
    flex: 0.1,
    // backgroundColor: colors.appDarkBlue
  },
  mapView: {
    flex: 1,
  },
  backgroundColorView: {
    position: "absolute",
    height: hp(25),
    // top: hp(10),
    zIndex: 1,
    alignSelf: "center",
    backgroundColor: "red",
    // backgroundColor: 'rgba(255,255,255,0)',
    // flex: 1,
  },
  map: {
    flex: 1,
  },
  textContainer: {
    fontSize: wp(4.7),
    color: colors.white,
  },
  uperView: {
    position: "absolute",
    top: wp(5),
    height: wp(25),
    width: wp(90),
    backgroundColor: "#FEFEFE",
    alignSelf: "center",
    borderRadius: wp(3),
  },
  middleView: {
    position: "absolute",
    top: wp(35),
    height: wp(70),
    width: wp(90),
    backgroundColor: colors.white,
    alignSelf: "center",
    borderRadius: wp(3),
  },
  lastView: {
    position: "absolute",
    top: wp(108),
    height: wp(35),
    width: wp(90),
    backgroundColor: colors.white,
    alignSelf: "center",
    borderRadius: wp(3),
  },
  uperViewText: {
    height: "40%",
    width: "100%",
    // backgroundColor: 'red',
    position: "absolute",
    // top: wp(4),
    alignItems: "center",
    justifyContent: "center",
  },
  uperViewSlider: {
    height: "35%",
    width: "100%",
    // backgroundColor: 'green',
    position: "absolute",
    top: wp(10),
    alignItems: "center",
    justifyContent: "center",
  },
  sliderText: {
    height: "20%",
    width: "100%",
    // backgroundColor: 'pink',
    position: "absolute",
    top: wp(19),
    alignItems: "center",
    justifyContent: "center",
  },
  middleViewText: {
    height: "20%",
    width: "100%",
    // backgroundColor: 'green',
    position: "absolute",
    // top: wp(4),
    alignItems: "center",
    justifyContent: "center",
  },
  uperViewTextStyle: {
    position: "absolute",
    top: wp(4),
    fontSize: wp(4.5),
    fontWeight: "500",
  },
  flatlistView: {
    height: "75%",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: 'pink',
    position: "absolute",
    top: wp(14),
  },
  buttonStyles: {
    borderRadius: wp(7),
    height: hp(8),
    width: "90%",
    marginBottom: wp(4),
  },
  titleStyles: {
    color: colors.white,
    fontSize: wp(4),
    fontWeight: "bold",
  },
  buttonContainer: {
    height: "10%",
    width: "90%",
    alignSelf: "center",
    justifyContent: "flex-end",
    // backgroundColor: colors.white,
    alignItems: "center",
    borderRadius: wp(3),
    position: "absolute",
    top: wp(160),
  },
  menuView: {
    flexDirection: "row",
    marginTop: 20,
    justifyContent: "space-between",
    paddingHorizontal: 20,
    // backgroundColor:'red'
  },
  menuTouch: {
    height: hp(4.9),
    width: wp(25),
    backgroundColor: colors.buttonColor,
    borderRadius: wp(3.6),
    flexDirection: "row",
  },
  menuText: {
    textAlign: "center",
    color: "#fff",
    paddingTop: wp(3),
  },
  ratingView: {
    alignItems: "flex-start",
    marginTop: wp(-3.7),
    marginLeft: hp(1.8),
  },
  textView: {
    height: hp(5),
    width: wp(100),
    flexDirection: "row",
    paddingHorizontal: wp(5),
    justifyContent: "space-between",
    // marginTop: hp(1),
    // backgroundColor: "red",
  },
  textViewLeft: {
    height: "100%",
    width: "50%",
    // backgroundColor: "green",
  },
  textViewRight: {
    height: "100%",
    width: "50%",
    // justifyContent: "center",
    paddingLeft: wp(22),
    // backgroundColor: "blue",
  },
  styleFont: {
    fontSize: wp(2.8),
  },
  imageView: {
    flexDirection: "row",
    paddingHorizontal: wp(5.5),
    marginTop: wp(1.5),
  },
  imageStyle: {
    height: hp(7),
    width: wp(14),
    borderRadius: wp(2),
    marginRight: wp(2),
  },
  calenderMenu: {
    height: hp(1.7),
    width: wp(5),
    tintColor: "#fff",
    marginTop: hp(1.5),
    marginLeft: hp(1.7),
    resizeMode: "contain",
  },
  imageModelStyle: {
    width: wp(13),
    height: hp(6),
    marginRight: wp(1.4),
    borderRadius: hp(0.5),
  },
  modal: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#2196f3",
    justifyContent: "center",
    padding: 10,
  },
  touchableButton: {
    width: "70%",
    padding: 10,
    backgroundColor: "#f06292",
    marginBottom: 10,
    marginTop: 30,
  },
  image: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  image1: {
    width: "100%",
    height: "100%",
    // flex:1,
    // height:hp(60),
    // width:wp(86),
    resizeMode: "cover",
    borderRadius: hp(2),
  },
  modalContainer: {
    width: "90%",
    height: "60%",
  },
  modelView: {
    // flex:0.8,
    alignItems: "center",
    backgroundColor: "transparent",
    height: hp(70),
    width: wp(90),
    // borderRadius: hp(10),
    marginTop: hp(15),
    // borderColor: "#fff",
    alignSelf: "center",
    // justifySelf:'center'
  },
  crossImage: {
    height: hp(3),
    width: hp(3),
    tintColor: colors.white,
    // alignSelf:'center',
    // marginTop:3.5,
  },
  crosBg: {
    // backgroundColor:colors.buttonColor,
    // height:hp(13),
    // width:hp(13),
    position: "absolute",
    zIndex: 1,
    right: 20,
    top: 15,
    // borderRadius:5,
  },
});
export default Styles;
